### PR TITLE
added sha256 hashing

### PR DESCRIPTION
**Pull request by light-bringer**

### CODE REVIEW

**Comment by light-bringer** [comment]
@smuraligs  checkout this PR

**Comment by lethalbrains** [comment]
@light-bringer Though technically this is fine, the package has been named md5 generator and hence there is no point in adding more cryptographic algorithm to this one. Better create a new repo for multiple algorithms.

**Comment by light-bringer** [comment]
@lethalbrains  so do I create a new package or repo for that? i was thinking to rename the package accordingly if that PR was accepted

**Comment by light-bringer** [comment]
@lethalbrains  hey I am adding it to the freshers module cherryworks, I will be wrapping up into a REST call so that whole floor can use the service

**Pull request closed without merging**
